spring:
  datasource:
    url: jdbc:h2:mem:history;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: history
        hbm2ddl:
          create_namespaces: true
    open-in-view: false

